### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Fer4code** [vscodeshift/material-ui-snippets#14]
- Issue Type: `Performance`
- Extension Name: `material-ui-snippets`
- Extension Version: `3.2.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.45.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\vscodeshift.material-ui-snippets-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jedwards1211** [comment]
Thanks for reporting this, does it happen when you select a snippet and it's applying it, or just when the completions menu is loading, or?

**Comment by Fer4code** [comment]
When the completation menu was loading happened to me

**Comment by jedwards1211** [comment]
Sigh, VSCode's completion item provider API design is part of the problem.  I have to provide all the edits that the item will make up front -- I can't wait to provide them until it's selected.  This means that I have to go ahead and parse the file and construct which imports need to be added for every snippet when building stuff for that menu, which is why it's so slow.

I'll investigate ways to work around this though...I guess until then I could add an option to disable adding the imports automatically.

Meanwhile @F3RN4ND02 @oliviertassinari could you guys upvote https://github.com/microsoft/vscode/issues/96779?

**Comment by oliviertassinari** [comment]
@jedwards1211 I have a 100% CPU issue with my VScode, from time to time. I haven't investigated the issue yet, the next time I experience it, I will try to pinpoint the origin.

**Comment by jedwards1211** [comment]
Okay I added an option to turn off automatic imports.  Should solve the perf issues but let me know if it doesn't.  Next I will add commands that do the same thing as snippets with automatic imports (but not doing the extra work to compute automatic imports until you run a command).

**Comment by jedwards1211** [comment]
Okay now in version 3.3.0 there are also commands you can use to insert the snippets; you shouldn't have the same performance problems with the commands.
