### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pablohdzvizcarra** [vscodeshift/material-ui-snippets#16]
- Issue Type: `Performance`
- Extension Name: `material-ui-snippets`
- Extension Version: `3.2.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.45.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\segui\vscodeshift.material-ui-snippets-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jedwards1211** [comment]
@PabloHdzVizcarra thanks for the report.  I've made a workaround for this already, though I need to add it to the README.  (I worry not everyone will see it there either?)

Go to the settings for `material-ui-snippets` and uncheck **Add Completion Imports**.  I'm waiting on some VSCode API improvements to get released to be able to automatically add imports without causing this performance issue.

Also I need to add editor commands that will insert the templates and automatic imports, since commands wouldn't do any work until you invoke them.

**Comment by jedwards1211** [comment]
Okay now in version 3.3.0 there are also commands you can use to insert the snippets; the commands will add the missing imports but you shouldn't have the same performance problems as with the completions.
